## BACKOFFICE ##

# News #

list-news:
    pattern:  /admin/list-news
    defaults: { _controller: SalleAdminBundle:BackOffice/ListNews:index }

edit-news:
    pattern: /admin/edit-news/{id}
    defaults: { _controller: SalleAdminBundle:BackOffice/EditNews:index }

add-new:
    pattern: /admin/add-new
    defaults: { _controller: SalleAdminBundle:BackOffice/AddNews:index }

# Images #

list-images:
    pattern:  /admin/list-images
    defaults: { _controller: SalleAdminBundle:BackOffice/ListImages:index }

add-image:
    pattern: /admin/add-image
    defaults: { _controller: SalleAdminBundle:BackOffice/AddImage:index }

# Comments #

list-comments:
    pattern: /admin/list-comments
    defaults: { _controller: SalleAdminBundle:BackOffice/ListComments:index }

# Flash #

list-flash:
    pattern: /admin/list-flash
    defaults: { _controller: SalleAdminBundle:BackOffice/ListFlash:index }

add-flash:
    pattern: /admin/add-flash
    defaults: { _controller: SalleAdminBundle:BackOffice/AddFlash:index }

edit-flash:
    pattern: /admin/edit-flash/{id}
    defaults: { _controller: SalleAdminBundle:BackOffice/EditFlash:index }

# Events #

list-events:
    pattern: /admin/list-events
    defaults: { _controller: SalleAdminBundle:BackOffice/ListEvents:index }

add-event:
    pattern: /admin/add-event
    defaults: { _controller: SalleAdminBundle:BackOffice/AddEvent:index }

edit-event:
    pattern: /admin/edit-event/{id}
    defaults: { _controller: SalleAdminBundle:BackOffice/EditEvent:index }

# Patros #

list-patros:
    pattern: /admin/list-patros
    defaults: { _controller: SalleAdminBundle:BackOffice/ListPatro:index }

add-patro:
    pattern: /admin/add-patro
    defaults: { _controller: SalleAdminBundle:BackOffice/AddPatro:index }

edit-patro:
    pattern: /admin/edit-patro/{id}
    defaults: { _controller: SalleAdminBundle:BackOffice/EditPatro:index }



## FRONT ##

home:
    pattern: /
    defaults: { _controller: SalleAdminBundle:Home:index }

galeria:
    pattern: /galeria
    defaults: { _controller: SalleAdminBundle:Galeria:index }

imagen:
    pattern: /imagen/{id}
    defaults: { _controller: SalleAdminBundle:Imagen:index }

quienes-somos:
    pattern: /quienes-somos
    defaults: { _controller: SalleAdminBundle:Somos:index }

radio:
    pattern: /radio
    defaults: { _controller: SalleAdminBundle:Radio:index }

noticia:
    pattern: /noticia/{id}
    defaults: { _controller: SalleAdminBundle:SingleNew:index }

buscar:
    pattern: /buscar
    defaults: { _controller: SalleAdminBundle:SearchResults:index }

patro:
    pattern: /patrocinadores
    defaults: { _controller: SalleAdminBundle:Patro:index }

equipo:
    pattern: /equipo
    defaults: { _controller: SalleAdminBundle:Equipo:index }


