## BACKOFFICE ##

# News #

list-news:
    pattern:  /admin/list-news
    defaults: { _controller: SalleAdminBundle:BackOffice/ListNews:index }

edit-news:
    pattern: /admin/edit-news
    defaults: { _controller: SalleAdminBundle:BackOffice/EditNews:index }

add-new:
    pattern: /admin/add-new
    defaults: { _controller: SalleAdminBundle:BackOffice/AddNews:index }



## FRONT ##

home:
    pattern: /
    defaults: { _controller: SalleAdminBundle:Home:index }

galeria:
    pattern: /galeria
    defaults: { _controller: SalleAdminBundle:Galeria:index }

quienes-somos:
    pattern: /quienes-somos
    defaults: { _controller: SalleAdminBundle:Somos:index }

radio:
    pattern: /radio
    defaults: { _controller: SalleAdminBundle:Radio:index }

noticia:
    pattern: /noticia/{id}
    defaults: { _controller: SalleAdminBundle:SingleNew:index }

buscar:
    pattern: /buscar
    defaults: { _controller: SalleAdminBundle:SearchResults:index }
