parameters:
#    salle_admin.example.class: Salle\AdminBundle\Example

services:
#    salle_admin.example:
#        class: %salle_admin.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
