security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    providers:
        in_memory:
            memory:
                users:
                    #user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            pattern:    ^/
            logout:
                path:   /logout
                target: /login
            anonymous: ~
            http_basic:
                realm: "Secured Demo Area"
            form_login:
                login_path:  login
                check_path:  login_check

    access_control:
        - { path: ^/admin/*, roles: ROLE_ADMIN }
