<?php

namespace Salle\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ComentarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComentarioRepository extends EntityRepository
{
	public function findAllComments($offset, $results)
    {
        
        $query = $this->createQueryBuilder('n')
		    ->orderBy('n.fecha', 'DESC')
            ->setFirstResult($results * $offset)
            ->setMaxResults($results)
		    ->getQuery();
		 
		$comments = $query->getArrayResult();

		return $comments;
    }

    public function getNumberComments()
    {
    	$query = $this->createQueryBuilder('n')
    		->select('count(n.id)');

    	$count = $query->getQuery()->getSingleScalarResult();

    	return $count;
    }

    public function findNoticiaComments ($noticia, $offset, $results)
    {
        
        $query = $this->createQueryBuilder('n')
            ->orderBy('n.fecha', 'DESC')
            ->where('n.noticia = :noticia')
            ->setParameter('noticia', $noticia)
            ->setFirstResult($results * $offset)
            ->setMaxResults($results)
            ->getQuery();
         
        $comments = $query->getArrayResult();

        return $comments;
    }
}
