<?php

namespace Salle\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ComentarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComentarioRepository extends EntityRepository
{
	public function findAllComments($offset)
    {
        
        $query = $this->createQueryBuilder('n')
		    ->orderBy('n.fecha', 'DESC')
            ->setFirstResult(1 * $offset)
            ->setMaxResults(1)
		    ->getQuery();
		 
		$comments = $query->getArrayResult();

		return $comments;
    }

    public function getNumberComments()
    {
    	$query = $this->createQueryBuilder('n')
    		->select('count(n.id)');

    	$count = $query->getQuery()->getSingleScalarResult();

    	return $count;
    }
}
