<?php

namespace Salle\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EquipoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipoRepository extends EntityRepository
{
	public function findAllEquipo($offset, $results)
    {
        
        $query = $this->createQueryBuilder('n')
		    ->orderBy('n.nombre', 'DESC')
            ->setFirstResult($results * $offset)
            ->setMaxResults($results)
		    ->getQuery();
		 
		$equipo = $query->getArrayResult();

		return $equipo;
    }

    public function countEquipo ()
    {

        $query = $this->createQueryBuilder('n')
            ->select('count(n.id)')
            ->getQuery();
         
        $count = $query->getSingleScalarResult();

        return $count;
    }
}
