<?php

namespace Salle\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ImagenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImagenRepository extends EntityRepository
{

	public function findAllImages($offset)
    {
        
        $query = $this->createQueryBuilder('n')
		    ->orderBy('n.fecha', 'DESC')
            ->setFirstResult(1 * $offset)
            ->setMaxResults(1)
		    ->getQuery();
		 
		$imagenes = $query->getArrayResult();

		return $imagenes;
    }

    public function countImagenes ()
    {
        $query = $this->createQueryBuilder('n')
            ->select('count(n.id)')
            ->getQuery();
         
        $count = $query->getSingleScalarResult();

        return $count;
    }
}
